### ISSUE TITLE
User Account Autonomy

### ISSUE THREAD

**Issue by adamstallard** [swiftdemand/protocol#1]
We could modify this:  https://github.com/neotracker/neotracker-wallet and host it as a static page that matches the rest of our site. (I actually like this one better: https://neowallet.cn/  but I couldn't find the source code).  The idea is to have a single page app that handles their wallet file, but doesn't interact with our web server, but instead interacts with their local wallet file (and creates one if necessary).   Whenever someone wants to send swifts (including for the store)--we send them to that page--we can even populate the price and "to" address for them.  It will access their wallet file; it will know which wallet file (in case of multiple users on the same computer) based on a "username" parameter we send in the url get string.

When they're returned to the calling page, a wallet address parameter is added to the url so the swiftdemand site can record their wallet address; that way the user never has to enter it themselves. (It will be needed for the "claim" button https://github.com/swiftdemand/protocol/issues/5)

From a user's POV, this just adds an "enter your password" step to complete a purchase, and then there's an additional notification they receive later that the seller receive the funds.  See https://github.com/swiftdemand/protocol/issues/4  They will see that a wallet file is being saved on their computer, but that's all they need to know about wallets.

**Comment by zaguios** [comment]
Here is my proposal for solving this issue while still allowing SwiftDemand to maintain its current functionality.

## When you click “Sign Up” your computer performs some special actions locally
1. A private/public key pair is generated on your machine
2. Your raw private key is encrypted with your password
3. The encrypted private key and public key are sent to SwiftDemand to be stored in your account
4. The encrypted private key is stored locally on your machine
5. A secret password is generated by SwiftDemand and sent to your computer
6. Your raw private key is encrypted with the secret password
7. This encrypted version of your private key is also stored locally on your device, but NOT on SwiftDemand

## When you click Send Swifts your computer performs some special actions
1. The secret password generated by SwiftDemand is sent to your device
2. The secret password is used to decrypt your private key locally
3. The transaction that corresponds to what you wanted to do is sent to your device
4. The transaction is automatically signed with your private key
5. The signed transaction is relayed to SwiftDemand

## Security wise what does this mean?

1. If a hacker gains access SwiftDemand they can only access the encrypted private keys which are useless without your password.
2. SwiftDemand is unable to make any transaction without your consent as the private key that was encrypted by our random password is only stored locally on your machine.
3. If you wish to recover your account it can be done so long as you are using a computer that you previously used to log into SwiftDemand. (We can send you our secret passcode which can be used to decrypt your private key on your device)
4. If someone hacks your machine they will only be able to see your private keys that were encrypted by your password or our randomly generated password. This will be useless to the attacker without access to one of those passwords.

### How will this change how I use SwiftDemand? 
From a user perspective everything will appear exactly the same. The only thing to note is that it is possible to get completely locked out of your account if you forget your password and you lose all computers you used to sign into SwiftDemand.
