### ISSUE TITLE
Notify swiftdemand users of completed transfers

### ISSUE THREAD

**Issue by adamstallard** [swiftdemand/protocol#4]
A service that can accept info about an attempted transaction and then notify subscribers when it's been confirmed on the blockchain.

From the referring page, we record that a sale was attempted.  The backend calls the service.  The buyer and the seller will both see notifications when the transaction is confirmed.  Similar notifications should happen with transfers.

**Comment by zaguios** [comment]
This can remain fairly simple.

1. Users send us a signed transaction as specified in #1 
2. We broadcast the transaction to the nodes
3. We store the transaction in the database and set the a new field on purchase called `status` to `pending`
4. We have a job that regularly checks the most recent blocks to see which pending transactions were included on the chain.
5. If we see the transaction on the chain we set the `status` from `pending` to `approved` and then update everything on SwiftDemand accordingly.

There is a trade-off here. I would like to instantly grant users access to the product/service that they purchased without waiting for confirmations. This does open us up to double spend attacks where the user sends off a custom transaction at the same time as the one made through SwiftDemand, but for smaller transactions we can insure this with central SwiftDemand funds.
